### ISSUE TITLE
"Invalid expression: b:oldfoldmethod" on exiting ListMode

### ISSUE THREAD

**Issue by paanvaannd** [bwhelm/vim-listmode#1]
# Environment
* Linux Mint v19.3
* `neovim` v.0.4.3
* installed using `vim-plug`
* installed [`kana/vim-textobj-user`](https://github.com/kana/vim-textobj-user) as well

Relevant settings in `~/.config/nvim/init.vim`:
```
let g:ListMode_folding=1
```

# Steps to reproduce
1. Enter ListMode (i.e. `<Leader>lm`)
2. Attempt to leave ListMode (i.e. repeat above command while in ListMode)
3. Following error is shown:
```
Error detected while processing function listmode#ToggleListMode[11]..<SNR>182_ListModeOff:
line   36:
E121: Undefined variable: b:oldfoldmethod
E15: Invalid expression: b:oldfoldmethod
```

Please let me know if any further information would be necessary to try to troubleshoot the issue.

**Comment by bwhelm** [comment]
Thanks for reporting this. I used to have some code for allowing the folding of lists that I subsequently removed (in commit 1c6095bf) because I didn’t find it useful. This error is an artifact of that removal; the solution is to remove that code completely. This should now be fixed in commit 39e9b0b74f12dac8fcb8cc225aa200e70aa5cab7.

**Comment by paanvaannd** [comment]
Ah... I was actually looking for that exact feature and was about to file another issue since the list folding was not working. I can't seem to find another plugin or method to do this otherwise.

Any chance on re-implementing it or advice on a DIY solution?

I updated the plugin and the error no longer occurs now, though, so I'm closing this issue.

**Comment by bwhelm** [comment]
You could just add everything back from those two commits referenced in my last comment. I don’t remember exactly why I deleted it other than that I ended up never using it. It may work well enough for you, at least in most cases.
